### ISSUE TITLE
Maths examples verified

### ISSUE THREAD

**Issue by mtnygard** [coni2k/PlantUML#2]
Readme states that the math examples are included but not verified.

I have verified that the examples here render correctly, once the (quite unclear) instructions from https://plantuml.com/ascii-math are followed.

To verify:

1. Download the basic [plantuml.jar](http://sourceforge.net/projects/plantuml/files/plantuml.jar/download)
1. Download the additional [jlatexmath support jars](http://beta.plantuml.net/plantuml-jlatexmath.zip)
1. Unzip the extra jars into the same directory as plantuml.jar
1. Make a wrapper script (see below) to run PlantUML with the extra jars on classpath.

```
#! /usr/bin/env bash
CLASSPATH="~/bin/batik-all-1.7.jar:~/bin/jlatexmath-minimal-1.0.3.jar:~/bin/jlm_cyrillic.jar:~/bin/jlm_greek.jar"
java -cp $CLASSPATH -jar ~/bin/plantuml.jar "$@"
```

I'm adding this as an issue in case you want to include these instructions in the readme or a supplemental doc.

**Comment by coni2k** [comment]
I downloaded the zip and unzipped the files next to plantuml.jar and it worked in VS Code!
I didn't have to do the last item, maybe that's necessary if you're executing from command line?

So, I updated Readme with the following:

* To be able draw "Math" formulas (examples under Chapter 13)
  * Download the additional [JLatexMath support jars](http://beta.plantuml.net/plantuml-jlatexmath.zip) from PlantUML website
  * Unzip the extra jars into the same directory as plantuml.jar
